### ISSUE TITLE
It seems like doesnt support go1.18?

### ISSUE THREAD

**Issue by mtcoafun** [guyarb/golang-test-annoations#18]
In action readme, the go version is set with `go1.14.x`,
then I change it to 
```yaml
jobs:
  full_ci:
    strategy:
      matrix:
        go-version: [ 1.18 ]
```
but it didnt work in my workflow pipline...
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/50589627/161271377-f15e79eb-95c7-4d42-b252-98aec237d076.png">
